# Digital Banking System Configuration

app.name= End to End Digital Banking System
app.version=1.0.0
app.author=Dawood

# Bank Information
bank.name = Prime Secure Bank

# Currency Settings
currency=INR
currency.symbol=Rs.

# Account Rules
savings.min.balance=0
current.overdraft.limit=500

# Transaction Rules
deposit.limit=100000
withdraw.limit=5000
transfer.limit=50000

# System Settings
date.format=ISO-8601
system.mode=development