# Digital Banking System Configuration

app.name= End to End Digital Banking System
app.version=1.0.0
app.author=Dawood

# Bank Information
bank.name = Prime Secure Bank

# Currency Settings
currency=INR
currency.symbol=₹

# Account Rules
savings.min.balance=500
current.overdraft.limit=10000

# Transaction Rules
max.transaction.limit=50000

# System Settings
date.format=dd-MM-yyyy HH:mm:ss
system.mode=development